name: Docker

on:
  push:
    branches:
      - main
      - feat/docker

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/pleisto/yuren-7b/yuren-7b:latest